### ISSUE TITLE
Errors in recoveries for Piaui for 6/19

### ISSUE THREAD

**Issue by akatz2** [wcota/covid19br#55]
Greetings.  Thank you again for your work.  Unfortunately, I believe the number of recoveries for 6/19 for Piaui is incorrect.  The latest change moves the recoveries from 734 to 13029.  Per the state reporting on twitter (https://twitter.com/GovernodoPi/status/1274495236148953088?s=20), I believe the current number should be 821.

**Comment by wcota** [comment]
Thanks again! I will to see what to do since they insist in using this large number of recovered individuals. Each state adopts a different criteria and it looks like that they are now using the same of the Ministry of Health: cases - deaths - hospitalized.

For PI, today they confirmed 15269 cases, 517 deaths and there are 827 hospitalized people. So, 15269-517-827 = 13925 is their reported number of recovered individuals (https://datastudio.google.com/reporting/a6dc07e9-4161-4b5a-9f2a-6f9be486e8f9/page/3PzLB)

**Comment by CSSEGISandData** [comment]
@wcota Thank you.  I apologize for my lack of prowess in Portuguese, but is there a fundamental difference between "Altas Médicas" and "Recuperados"?

**Comment by akatz2** [comment]
@wcota Thank you.  I apologize for my lack of proficiency in Portuguese, but is there a fundamental difference between "Altas Médicas" and "Recuperados"?  Or is it more likely that, as you noted above, this is just a fundamental change in their reporting methodology for their dashboard vs. their press releases?

**Comment by wcota** [comment]
Don't worry! :) 
In "Altas médicas" they have the accumulated number of people that were hospitalized and then released (in portuguese we say that the person "teve/recebeu alta"). 
As they don't track all the confirmed cases to know if they are cured or not, usually they make a estimate of recovered individuals by cases - deaths - hospitalized, which is obviously wrong in this case. Some states do it a little better and consider the incubation period as well, but all those "methodologies" are not clear and explained anywhere.

Anyway, in this panel they put this "altas médicas" after the graphs:

Suspeitos Internados (hospitalized suspects)
827
Leitos Clínicos Ocupados (clinical beds in use)
522
Leitos de UTI Ocupados (UCI beds in use)
287
Leitos de Estabilização Ocupados (stabilization beds in use)
18
**Altas Médicas Acumuladas (number of people released from the hospital)
861**
Recuperados (recovered individuals)
13925

**Comment by akatz2** [comment]
@wcota Thank you!!!
